### ISSUE TITLE
Cosmology discrepancy between config.yml and metrics.py

### ISSUE THREAD

**Issue by EiffL** [LSSTDESC/tomo_challenge#6]
Whil trying to validate my own Fisher matrices, I came accross what appear to be discrepancies between the cosmology used by firecrown from the `config.py`:
```
# This section defines fiducial values for all parameters.
parameters:
  Omega_k: 0.0
  Omega_c: 0.27
  Omega_b: 0.045
  h: 0.67
  n_s: 0.96
  sigma8: 0.8404844953840714
  w0: -1.0
  wa: 0.0
```

and the code in `metrics.py`:
```
    cosmo = ccl.Cosmology(
        Omega_c=0.22,
        Omega_b=0.0447927,
        h=0.71,
        n_s=0.963,
        sigma8=0.8,
    )
```
I'm not sure how much it matters. For the Fisher, I assume the data vector from the sacc file is being ignored anyway, but I guess the covariance matrix computed in `metrics.py` get used, and it would then be at a different cosmology.
